"""2AFC temperature contrast-hardening for the A1 temperature census candidate (12f/12g standard).

Sibling of `run_2afc_mode_hardening` for the temperature axis (which is NOT a pure-mode corpus).
Pairs each t09 (hot) gen with a same-topic t03 (cold) gen; the judge picks which was produced at
a HIGHER sampling temperature (more random/less predictable word choices). Position randomized
(deterministic RNG). Above-chance accuracy hardens the temperature candidate's judge rung
(census gap = internals − max(content, likelihood, JUDGE)). Same Wilson/binom/usage machinery and
Fable→opus fallback as the mode tool; verify usage.calls>0.

Reads {data-root}/vmb_a1_{model}_t03 and _t09 metadata.json. maybe_decode on every text (M6 byte-BPE).

    python -m anamnesis.scripts.run_2afc_temperature_hardening --model dsv2-lite \
        --data-root $RUNS --out-json <out.json>
"""
from __future__ import annotations

import argparse
import json
import math
import random
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from anamnesis.analysis.battery.text_decode import maybe_decode

JUDGE_MODEL = "claude-fable-5"
FALLBACK_MODEL = "claude-opus-4-8"
MAX_RETRIES = 3

_lock = threading.Lock()
_usage = {"input_tokens": 0, "output_tokens": 0, "calls": 0, "fallbacks": 0}

TEMP_DESC = ("produced at a HIGHER sampling temperature — its word choices are more random, "
             "surprising, and less predictable; a lower-temperature text is more deterministic, "
             "repetitive, and 'safe' in its phrasing.")


def _wilson(k: int, n: int) -> tuple[float, float]:
    if n == 0:
        return (0.0, 1.0)
    z = 1.96
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    hw = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (round((c - hw) / d, 4), round((c + hw) / d, 4))


def _binom_p_ge(k: int, n: int, p0: float = 0.5) -> float:
    from math import comb
    return round(sum(comb(n, i) * p0**i * (1 - p0)**(n - i) for i in range(k, n + 1)), 5)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="e.g. dsv2-lite")
    ap.add_argument("--data-root", type=Path, required=True, help="dir with vmb_a1_{model}_t0{3,9}/")
    ap.add_argument("--hot", default="t09")
    ap.add_argument("--cold", default="t03")
    ap.add_argument("--n", type=int, default=None)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--seed", type=int, default=20260712)
    ap.add_argument("--judge-model", default=JUDGE_MODEL)
    ap.add_argument("--out-json", type=Path, required=True)
    args = ap.parse_args()
    args.out_json.parent.mkdir(parents=True, exist_ok=True)

    import anthropic
    client = anthropic.Anthropic()
    system = ("You are an expert text analyst. You will be shown TWO texts (A and B) generated by "
              "the same language model on the same topic, at DIFFERENT sampling temperatures. "
              f"Exactly ONE was {TEMP_DESC}\n\nDecide which text (A or B) was produced at the "
              "higher temperature. Respond with ONLY a JSON object (no markdown fencing): "
              "{\"choice\": \"A\" or \"B\", \"confidence\": <1-5>}")

    def call(model, topic, a, b):
        for attempt in range(MAX_RETRIES):
            try:
                r = client.messages.create(model=model, max_tokens=1500, system=system,
                                           messages=[{"role": "user", "content":
                                                      f"Topic: {topic}\n\n=== TEXT A ===\n{a}\n\n=== TEXT B ===\n{b}"}])
                with _lock:
                    _usage["input_tokens"] += r.usage.input_tokens
                    _usage["output_tokens"] += r.usage.output_tokens
                    _usage["calls"] += 1
                raw = next((bl.text for bl in r.content if getattr(bl, "type", None) == "text"), None)
                if raw is None:
                    return None
                raw = raw.strip().strip("`").lstrip("json").strip()
                obj = json.loads(raw)
                return obj.get("choice") if obj.get("choice") in ("A", "B") else None
            except anthropic.APIStatusError as e:
                if e.status_code in (429, 500, 529):
                    time.sleep(2.0 * (attempt + 1)); continue
                return None
            except Exception:  # noqa: BLE001
                time.sleep(2.0 * (attempt + 1))
        return None

    def texts_of(tag):
        md = json.loads((args.data_root / f"vmb_a1_{args.model}_{tag}" / "metadata.json").read_text())
        gens = sorted(md["generations"], key=lambda g: g["generation_id"])
        for g in gens:
            g["_text"] = maybe_decode(g.get("generated_text", ""))
        return gens

    rng = random.Random(args.seed)
    hot = texts_of(args.hot)
    if args.n:
        hot = hot[:args.n]
    cold = texts_of(args.cold)
    items = []
    for i, g in enumerate(hot):
        cands = [d for d in cold if d["topic_idx"] == g["topic_idx"]]
        if not cands:
            continue
        d = cands[i % len(cands)]
        pos = rng.choice(("A", "B"))
        items.append({"pair_id": f"{args.model}_temp_{i:03d}", "topic": g["topic"],
                      "A": g["_text"] if pos == "A" else d["_text"],
                      "B": d["_text"] if pos == "A" else g["_text"],
                      "target_pos": pos})

    def judge(item):
        c = call(args.judge_model, item["topic"], item["A"], item["B"])
        used = args.judge_model
        if c is None:
            c = call(FALLBACK_MODEL, item["topic"], item["A"], item["B"])
            used = FALLBACK_MODEL
            with _lock:
                _usage["fallbacks"] += 1
        return {"pair_id": item["pair_id"], "choice": c or "FAILED",
                "correct": c == item["target_pos"], "judge": used}

    t0 = time.time()
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        res = list(ex.map(judge, items))
    ok = [r for r in res if r["choice"] != "FAILED"]
    k = sum(r["correct"] for r in ok)
    acc = k / max(len(ok), 1)
    out = {
        "arm": "2AFC temperature hardening (t09-vs-t03, higher-temperature discrimination)",
        "STATUS": "FIRST_READ_PENDING (C§8) — UNSTAMPED -> outer loop",
        "protocol": "temperature 2AFC (hot vs same-topic cold; which is higher-temperature)",
        "model": args.model, "hot": args.hot, "cold": args.cold,
        "judge_model": args.judge_model, "n": len(ok), "failed": len(res) - len(ok),
        "acc_2afc": round(acc, 4), "wilson95": _wilson(k, len(ok)),
        "binom_p_ge_chance": _binom_p_ge(k, len(ok)),
        "qualifies_070": bool(acc >= 0.70), "usage": _usage, "details": res,
    }
    args.out_json.write_text(json.dumps(out, indent=1))
    print(f"{args.model} temperature {args.hot}v{args.cold}: 2AFC acc {acc:.3f} "
          f"(n={len(ok)}, wilson {out['wilson95']}, p={out['binom_p_ge_chance']}, "
          f"{time.time()-t0:.0f}s)  calls={_usage['calls']}")
    if _usage["calls"] == 0:
        print("⚠ WARNING: 0 judge calls — check ANTHROPIC_API_KEY (silent auth no-op)")


if __name__ == "__main__":
    main()
