"""2AFC contrast-hardening / pole-vs-pole qualification for census mode candidates (12f/12g standard).

Blind k-way judge-invisibility is NOT sufficient for census membership; the standard is
discrimination-UNDER-CONTRAST. This runs the canonical 2AFC: each TARGET-mode gen is paired with a
same-topic, same-model distractor; the judge (claude-fable-5, opus-4-8 fallback) picks which of two
texts followed the target mode's procedure; position randomized (deterministic RNG). Above-chance
accuracy (with the internals-decode prior) hardens a trained-detector-rung candidate to membership.

Two uses, one tool:
  HARDENING       --distractors a,b,c,d  (cycled)  → target-vs-any-other 2AFC (census P).
  POLE-VS-POLE    --distractors b          (single) → target-vs-b qualification (14v-1 selection rule:
                  ≥.70 qualifies a steering pair). Run per candidate pair; any ≥.70 surfaces to desk.

M6 (dsv2-lite) stores generated_text byte-BPE encoded → maybe_decode on every text (else the judge
reads re-tokenized garbage). Reads corpora from {data-root}/vmb_a2_{model}_pure_{mode}/metadata.json.

Needs ANTHROPIC_API_KEY in env (pass via --env on node jobs; verify usage.calls>0 — silent auth
no-ops have happened). First-read -> outer loop; UNSTAMPED.

    python -m anamnesis.scripts.run_2afc_mode_hardening --model dsv2-lite --target-mode linear \
        --distractors analogical,contrastive,socratic,dialectical --data-root $RUNS \
        --out-json $BANK/arms/A3_dsv2/judge/linear_2afc_fable.json
"""
from __future__ import annotations

import argparse
import json
import math
import random
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from anamnesis.analysis.battery.text_decode import maybe_decode

# judge-facing mode descriptions (paraphrased from anamnesis/modes/run4_modes.py, format-constraint dropped)
MODE_DESC: dict[str, str] = {
    "linear": ("A clear forward sequence, each idea building on the last, laid out step by step "
               "from beginning to end with no backtracking or reconsidering of previous points."),
    "analogical": ("Explanation built primarily through extended analogies and parallels to other "
                   "domains — each key concept illuminated by a comparison from everyday life or another field."),
    "socratic": ("Exploration through a chain of questions and provisional answers: pose a question, "
                 "offer a tentative answer, use it to generate the next question; inquiry drives it forward."),
    "contrastive": ("Comparing and contrasting multiple perspectives — for each major point, at least "
                    "two viewpoints presented and their relative strengths and weaknesses weighed."),
    "dialectical": ("Propose a position, challenge it with the strongest counterarguments, then work "
                    "toward a revised understanding accounting for both the original position and its critiques."),
}

JUDGE_MODEL = "claude-fable-5"
FALLBACK_MODEL = "claude-opus-4-8"
MAX_RETRIES = 3

_lock = threading.Lock()
_usage = {"input_tokens": 0, "output_tokens": 0, "calls": 0, "fallbacks": 0}


def _wilson(k: int, n: int) -> tuple[float, float]:
    if n == 0:
        return (0.0, 1.0)
    z = 1.96
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    hw = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (round((c - hw) / d, 4), round((c + hw) / d, 4))


def _binom_p_ge(k: int, n: int, p0: float = 0.5) -> float:
    """one-sided P(X>=k) under Binom(n,p0)."""
    from math import comb
    return round(sum(comb(n, i) * p0**i * (1 - p0)**(n - i) for i in range(k, n + 1)), 5)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="e.g. dsv2-lite")
    ap.add_argument("--target-mode", required=True)
    ap.add_argument("--distractors", required=True, help="comma list; single = pole-vs-pole")
    ap.add_argument("--data-root", type=Path, required=True, help="dir with vmb_a2_{model}_pure_{mode}/")
    ap.add_argument("--n", type=int, default=None, help="cap on target gens (default all)")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--seed", type=int, default=20260712)
    ap.add_argument("--judge-model", default=JUDGE_MODEL)
    ap.add_argument("--out-json", type=Path, required=True)
    args = ap.parse_args()
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    distractors = [d.strip() for d in args.distractors.split(",")]
    tdesc = MODE_DESC[args.target_mode]

    import anthropic
    client = anthropic.Anthropic()
    system = ("You are an expert text analyst. You will be shown TWO texts (A and B) generated by a "
              "language model on the same topic. Exactly ONE was produced under an instruction to use "
              f"this processing mode:\n\n**{args.target_mode.capitalize()}**: {tdesc}\n\n"
              "Decide which text follows that mode. Respond with ONLY a JSON object (no markdown "
              "fencing): {\"choice\": \"A\" or \"B\", \"confidence\": <1-5>}")

    def call(model, topic, a, b):
        for attempt in range(MAX_RETRIES):
            try:
                r = client.messages.create(model=model, max_tokens=1500, system=system,
                                           messages=[{"role": "user", "content":
                                                      f"Topic: {topic}\n\n=== TEXT A ===\n{a}\n\n=== TEXT B ===\n{b}"}])
                with _lock:
                    _usage["input_tokens"] += r.usage.input_tokens
                    _usage["output_tokens"] += r.usage.output_tokens
                    _usage["calls"] += 1
                raw = next((bl.text for bl in r.content if getattr(bl, "type", None) == "text"), None)
                if raw is None:
                    return None
                raw = raw.strip().strip("`").lstrip("json").strip()
                obj = json.loads(raw)
                return obj.get("choice") if obj.get("choice") in ("A", "B") else None
            except anthropic.APIStatusError as e:
                if e.status_code in (429, 500, 529):
                    time.sleep(2.0 * (attempt + 1)); continue
                return None
            except Exception:  # noqa: BLE001
                time.sleep(2.0 * (attempt + 1))
        return None

    def texts_of(mode):
        md = json.loads((args.data_root / f"vmb_a2_{args.model}_pure_{mode}" / "metadata.json").read_text())
        gens = sorted(md["generations"], key=lambda g: g["generation_id"])
        for g in gens:
            g["_text"] = maybe_decode(g.get("generated_text", ""))
        return gens

    rng = random.Random(args.seed)
    tgt = texts_of(args.target_mode)
    if args.n:
        tgt = tgt[:args.n]
    others = {m: texts_of(m) for m in set(distractors)}
    items = []
    for i, g in enumerate(tgt):
        dmode = distractors[i % len(distractors)]
        cands = [d for d in others[dmode] if d["topic_idx"] == g["topic_idx"]]
        if not cands:
            continue
        d = cands[i % len(cands)]
        pos = rng.choice(("A", "B"))
        items.append({"pair_id": f"{args.model}_{args.target_mode}_{i:03d}", "topic": g["topic"],
                      "A": g["_text"] if pos == "A" else d["_text"],
                      "B": d["_text"] if pos == "A" else g["_text"],
                      "target_pos": pos, "distractor_mode": dmode})

    def judge(item):
        c = call(args.judge_model, item["topic"], item["A"], item["B"])
        used = args.judge_model
        if c is None:
            c = call(FALLBACK_MODEL, item["topic"], item["A"], item["B"])
            used = FALLBACK_MODEL
            with _lock:
                _usage["fallbacks"] += 1
        return {"pair_id": item["pair_id"], "choice": c or "FAILED",
                "correct": c == item["target_pos"], "distractor_mode": item["distractor_mode"], "judge": used}

    t0 = time.time()
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        res = list(ex.map(judge, items))
    ok = [r for r in res if r["choice"] != "FAILED"]
    k = sum(r["correct"] for r in ok)
    acc = k / max(len(ok), 1)
    by_d = {}
    for m in set(distractors):
        sel = [r for r in ok if r["distractor_mode"] == m]
        if sel:
            by_d[m] = round(sum(r["correct"] for r in sel) / len(sel), 3)
    out = {
        "arm": "2AFC mode hardening / pole-vs-pole qualification",
        "STATUS": "FIRST_READ_PENDING (C§8) — UNSTAMPED -> outer loop",
        "protocol": ("pole-vs-pole" if len(distractors) == 1 else "hardening (target-vs-cycled-distractors)"),
        "model": args.model, "target_mode": args.target_mode, "distractors": distractors,
        "judge_model": args.judge_model, "n": len(ok), "failed": len(res) - len(ok),
        "acc_2afc": round(acc, 4), "wilson95": _wilson(k, len(ok)),
        "binom_p_ge_chance": _binom_p_ge(k, len(ok)), "by_distractor": by_d,
        "qualifies_070": bool(acc >= 0.70), "usage": _usage, "details": res,
    }
    args.out_json.write_text(json.dumps(out, indent=1))
    print(f"{args.model} {args.target_mode} vs {distractors}: 2AFC acc {acc:.3f} "
          f"(n={len(ok)}, wilson {out['wilson95']}, p={out['binom_p_ge_chance']}, "
          f"{time.time()-t0:.0f}s) by_d={by_d}  calls={_usage['calls']}")
    if _usage["calls"] == 0:
        print("⚠ WARNING: 0 judge calls — check ANTHROPIC_API_KEY (silent auth no-op)")


if __name__ == "__main__":
    main()
