#!/usr/bin/env python3
"""Blind judge scoring of 8B generated texts using Claude Opus.

The judge sees the text and topic but NOT the system
prompt or intended mode. For each text, the judge rates it on 5 mode
dimensions (1-5) and classifies the primary mode.

Usage:
    python -m anamnesis.scripts.run_judge_scoring
    python -m anamnesis.scripts.run_judge_scoring --resume
    python -m anamnesis.scripts.run_judge_scoring --sig-dir path/to/sigs --output path/to/output.json

Outputs: outputs/analysis/8b_baseline/judge_scores.json
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np
from scipy.spatial.distance import cdist
from sklearn.preprocessing import StandardScaler

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ── Constants ────────────────────────────────────────────────────────────────

JUDGE_MODEL = "claude-sonnet-4-6"  # Sonnet for cost efficiency; Opus for max quality
VALID_MODES = ["linear", "analogical", "socratic", "contrastive", "dialectical"]
MAX_RETRIES = 3
RETRY_DELAY_BASE = 2.0
CALL_DELAY = 0.3

JUDGE_MODE_DESCRIPTIONS: dict[str, str] = {
    "linear": (
        "Sequential, forward-moving exposition. Ideas presented one after another, "
        "each building on the last. No backtracking, no reconsideration of previous "
        "points. Straightforward progression from start to finish."
    ),
    "analogical": (
        "Explanation driven by analogies and parallels to other domains. Key concepts "
        "are illuminated through comparisons to everyday life or other fields. "
        "Frequent use of 'it's like...', 'think of it as...', 'similarly in...' "
        "constructions. Understanding built through connections."
    ),
    "socratic": (
        "Exploration through questions and provisional answers. The text poses "
        "questions, offers tentative responses, then uses those answers to generate "
        "new questions. An inquiry-driven structure where questions guide the "
        "explanation forward."
    ),
    "contrastive": (
        "Explores topics by comparing and contrasting multiple perspectives or "
        "approaches. Presents different viewpoints side by side, evaluating their "
        "relative strengths and weaknesses. Frequent use of 'on the other hand', "
        "'whereas', 'in contrast' language."
    ),
    "dialectical": (
        "Proposes a clear position, then challenges it with counterarguments, "
        "then works toward a synthesis or revised understanding. Shows a "
        "thesis-challenge-revision structure. The text argues with itself, "
        "building through productive disagreement."
    ),
}


def _build_judge_system_prompt() -> str:
    mode_descriptions = []
    for i, (mode, desc) in enumerate(JUDGE_MODE_DESCRIPTIONS.items(), 1):
        mode_descriptions.append(f"{i}. **{mode.title()}**: {desc}")

    ratings_json = ",\n    ".join(f'"{m}": <1-5>' for m in VALID_MODES)
    mode_list = ", ".join(VALID_MODES)

    return (
        "You are an expert text analyst. You will be shown a text generated by a "
        "language model in response to a writing prompt. The model was given a "
        "specific processing mode instruction (which you do not know), and your job "
        "is to assess which processing mode(s) the text exhibits.\n\n"
        "Rate the text on each of these dimensions from 1 (not at all present) "
        "to 5 (strongly and consistently present throughout):\n\n"
        + "\n\n".join(mode_descriptions)
        + "\n\n"
        "After rating, classify which single mode BEST describes the overall text.\n\n"
        "Respond with ONLY a JSON object (no markdown fencing, no commentary):\n"
        "{\n"
        '  "ratings": {\n'
        f"    {ratings_json}\n"
        "  },\n"
        f'  "primary_mode": "<one of: {mode_list}>",\n'
        '  "confidence": <1-5>,\n'
        '  "reasoning": "<1 sentence explanation>"\n'
        "}"
    )


JUDGE_SYSTEM_PROMPT = _build_judge_system_prompt()


# ── Data loading ─────────────────────────────────────────────────────────────


def load_8b_generations(sig_dir: Path, core_only: bool = True) -> list[dict[str, Any]]:
    """Load generation metadata from per-sample JSON files."""
    json_files = sorted(sig_dir.glob("gen_*.json"))
    if not json_files:
        raise FileNotFoundError(f"No gen_*.json files in {sig_dir}")

    all_gens = []
    for jf in json_files:
        with open(jf) as f:
            meta = json.load(f)
        all_gens.append({
            "generation_id": meta["generation_id"],
            "mode": meta["mode"],
            "topic": meta["topic"],
            "generated_text": meta.get("generated_text", ""),
            "file_stem": jf.stem,
        })

    if core_only:
        # One rep per topic-mode pair (take first occurrence)
        seen: set[tuple[str, str]] = set()
        filtered = []
        for g in all_gens:
            key = (g["mode"], g["topic"])
            if key not in seen:
                seen.add(key)
                filtered.append(g)
        all_gens = filtered

    logger.info(f"Loaded {len(all_gens)} generations from {sig_dir}")
    return all_gens


# ── Scoring ──────────────────────────────────────────────────────────────────


def build_user_message(topic: str, text: str) -> str:
    return f"**Writing prompt:** {topic}\n\n**Generated text:**\n\n{text}"


def parse_judge_response(raw: str) -> dict[str, Any] | None:
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        first_newline = cleaned.index("\n")
        cleaned = cleaned[first_newline + 1:]
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3]
    cleaned = cleaned.strip()

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError:
        # Try to repair truncated reasoning field
        repair_match = re.search(r'("reasoning"\s*:\s*")', cleaned)
        if repair_match:
            truncated = cleaned[:repair_match.end()] + '(truncated)"}'
            try:
                data = json.loads(truncated)
            except json.JSONDecodeError:
                return None
        else:
            return None

    if not isinstance(data, dict):
        return None

    ratings = data.get("ratings")
    if not isinstance(ratings, dict):
        return None

    for mode in VALID_MODES:
        val = ratings.get(mode)
        if not isinstance(val, (int, float)) or not (1 <= val <= 5):
            return None

    primary = data.get("primary_mode")
    if primary not in VALID_MODES:
        return None

    confidence = data.get("confidence")
    if not isinstance(confidence, (int, float)) or not (1 <= confidence <= 5):
        confidence = 3 if confidence is None else None
        if confidence is None:
            return None

    reasoning = data.get("reasoning", "")
    if not isinstance(reasoning, str):
        reasoning = str(reasoning)

    return {
        "ratings": {m: int(ratings[m]) for m in VALID_MODES},
        "primary_mode": primary,
        "confidence": int(confidence),
        "reasoning": reasoning,
    }


def score_single_text(
    client: Any, topic: str, text: str,
) -> dict[str, Any] | None:
    user_msg = build_user_message(topic, text)

    for attempt in range(MAX_RETRIES):
        try:
            response = client.messages.create(
                model=JUDGE_MODEL,
                max_tokens=800,
                system=JUDGE_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_msg}],
            )
            raw_text = response.content[0].text
            parsed = parse_judge_response(raw_text)

            if parsed is not None:
                return parsed

            logger.warning(
                f"Attempt {attempt + 1}/{MAX_RETRIES}: parse failed. "
                f"Raw: {raw_text[:200]}"
            )
        except Exception as e:
            wait = RETRY_DELAY_BASE ** (attempt + 1)
            logger.warning(f"API error: {e}. Retrying in {wait:.0f}s...")
            time.sleep(wait)

    return None


# ── Analysis ─────────────────────────────────────────────────────────────────


def compute_summary(scores: list[dict[str, Any]]) -> dict[str, Any]:
    n = len(scores)
    if n == 0:
        return {"error": "No scores"}

    correct = sum(1 for s in scores if s["correct"])
    overall_accuracy = correct / n

    per_mode_accuracy: dict[str, dict[str, Any]] = {}
    for mode in VALID_MODES:
        mode_scores = [s for s in scores if s["mode_intended"] == mode]
        if mode_scores:
            mc = sum(1 for s in mode_scores if s["correct"])
            per_mode_accuracy[mode] = {
                "accuracy": mc / len(mode_scores),
                "n": len(mode_scores),
                "n_correct": mc,
            }

    purities = [s["mode_purity"] for s in scores]
    confidences = [s["judge_confidence"] for s in scores]

    confusion = np.zeros((5, 5), dtype=int)
    for s in scores:
        i_idx = VALID_MODES.index(s["mode_intended"])
        p_idx = VALID_MODES.index(s["primary_mode"])
        confusion[i_idx, p_idx] += 1

    correct_purities = [s["mode_purity"] for s in scores if s["correct"]]
    incorrect_purities = [s["mode_purity"] for s in scores if not s["correct"]]

    return {
        "overall_accuracy": overall_accuracy,
        "per_mode_accuracy": per_mode_accuracy,
        "mean_purity": float(np.mean(purities)),
        "std_purity": float(np.std(purities)),
        "mean_confidence": float(np.mean(confidences)),
        "confusion_matrix": confusion.tolist(),
        "confusion_labels": VALID_MODES,
        "mean_purity_when_correct": float(np.mean(correct_purities)) if correct_purities else 0.0,
        "mean_purity_when_incorrect": float(np.mean(incorrect_purities)) if incorrect_purities else 0.0,
    }


def compute_purity_signature_correlation(
    scores: list[dict[str, Any]], sig_dir: Path,
) -> dict[str, Any] | None:
    """Correlate judge purity with signature-space distances."""
    gen_ids = [s["generation_id"] for s in scores]
    features_by_id: dict[int, np.ndarray] = {}

    for gid in gen_ids:
        npz_path = sig_dir / f"gen_{gid:03d}.npz"
        if npz_path.exists():
            try:
                data = np.load(npz_path)
                features_by_id[gid] = data["features"]
            except Exception as e:
                logger.warning(f"Failed to load {npz_path}: {e}")

    if len(features_by_id) < 10:
        return None

    scored_with_sigs = [s for s in scores if s["generation_id"] in features_by_id]
    if len(scored_with_sigs) < 10:
        return None

    X = np.stack([features_by_id[s["generation_id"]] for s in scored_with_sigs])
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    modes = [s["mode_intended"] for s in scored_with_sigs]
    purities = np.array([s["mode_purity"] for s in scored_with_sigs])

    centroids: dict[str, np.ndarray] = {}
    for mode in VALID_MODES:
        mask = np.array([m == mode for m in modes])
        if mask.sum() > 0:
            centroids[mode] = X_scaled[mask].mean(axis=0)

    if len(centroids) < 5:
        return None

    distances = []
    for i, s in enumerate(scored_with_sigs):
        centroid = centroids[s["mode_intended"]].reshape(1, -1)
        sample = X_scaled[i].reshape(1, -1)
        distances.append(float(cdist(sample, centroid, metric="cosine")[0, 0]))

    distances_arr = np.array(distances)

    if np.std(purities) < 1e-10 or np.std(distances_arr) < 1e-10:
        correlation = 0.0
    else:
        correlation = float(np.corrcoef(purities, distances_arr)[0, 1])

    median_purity = float(np.median(purities))
    high_mask = purities >= median_purity
    low_mask = purities < median_purity

    return {
        "n_samples": len(scored_with_sigs),
        "purity_distance_correlation": correlation,
        "high_purity_mean_distance": float(distances_arr[high_mask].mean()) if high_mask.sum() > 0 else 0.0,
        "low_purity_mean_distance": float(distances_arr[low_mask].mean()) if low_mask.sum() > 0 else 0.0,
        "median_purity_split": median_purity,
    }


# ── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description="Judge scoring for 8B generated texts")
    parser.add_argument(
        "--sig-dir", type=str,
        default="outputs/runs/run_8b_baseline/signatures",
        help="Signature directory with gen_NNN.json files",
    )
    parser.add_argument(
        "--output", type=str,
        default="outputs/analysis/8b_baseline/judge_scores.json",
        help="Output path for judge scores",
    )
    parser.add_argument("--resume", action="store_true", help="Resume from partial run")
    parser.add_argument(
        "--model", type=str, default=JUDGE_MODEL,
        help=f"Judge model (default: {JUDGE_MODEL})",
    )
    args = parser.parse_args()

    # Update module-level model name if overridden
    import anamnesis.scripts.run_judge_scoring as _self
    _self.JUDGE_MODEL = args.model

    sig_dir = Path(args.sig_dir)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Validate API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        logger.error("ANTHROPIC_API_KEY not set")
        sys.exit(1)

    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    # Load generations
    generations = load_8b_generations(sig_dir, core_only=True)

    # Handle resume
    existing_scores: list[dict[str, Any]] = []
    scored_ids: set[int] = set()
    if args.resume and output_path.exists():
        try:
            with open(output_path) as f:
                data = json.load(f)
            existing_scores = data.get("scores", [])
            scored_ids = {s["generation_id"] for s in existing_scores}
            logger.info(f"Resuming: {len(scored_ids)} already scored")
        except (json.JSONDecodeError, KeyError):
            pass

    scores = list(existing_scores)
    failed_ids: list[int] = []
    to_score = [g for g in generations if g["generation_id"] not in scored_ids]

    logger.info(f"Scoring {len(to_score)} texts with {JUDGE_MODEL}")

    for i, gen in enumerate(to_score):
        gid = gen["generation_id"]
        mode = gen["mode"]
        topic = gen["topic"]
        text = gen["generated_text"]

        if not text:
            logger.warning(f"Empty text for gen_{gid:03d}, skipping")
            failed_ids.append(gid)
            continue

        logger.info(
            f"[{len(scores) + 1}/{len(generations)}] "
            f"gen_{gid:03d} ({mode}/{topic[:30]}...)"
        )

        result = score_single_text(client, topic, text)

        if result is None:
            logger.error(f"Failed to score gen_{gid:03d}")
            failed_ids.append(gid)
            continue

        intended_rating = result["ratings"][mode]
        other_ratings = [result["ratings"][m] for m in VALID_MODES if m != mode]
        purity = intended_rating - float(np.mean(other_ratings))

        scores.append({
            "generation_id": gid,
            "mode_intended": mode,
            "topic": topic,
            "ratings": result["ratings"],
            "primary_mode": result["primary_mode"],
            "judge_confidence": result["confidence"],
            "reasoning": result["reasoning"],
            "mode_purity": round(purity, 3),
            "correct": result["primary_mode"] == mode,
        })

        # Save incrementally
        if len(scores) % 10 == 0 or i == len(to_score) - 1:
            output = {
                "model": JUDGE_MODEL,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "n_scored": len(scores),
                "scores": scores,
            }
            with open(output_path, "w") as f:
                json.dump(output, f, indent=2, default=str)

        time.sleep(CALL_DELAY)

    # Final analysis
    logger.info("Computing summary...")
    summary = compute_summary(scores)

    logger.info("Computing purity-signature correlation...")
    correlation = compute_purity_signature_correlation(scores, sig_dir)

    # Save final
    output = {
        "model": JUDGE_MODEL,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "n_scored": len(scores),
        "n_failed": len(failed_ids),
        "failed_generation_ids": failed_ids,
        "scores": scores,
        "summary": summary,
        "purity_signature_correlation": correlation,
    }
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2, default=str)
    logger.info(f"Saved to {output_path}")

    # Print results
    print("\n" + "=" * 60)
    print("JUDGE SCORING RESULTS")
    print("=" * 60)
    print(f"\nOverall accuracy: {summary['overall_accuracy']:.1%}")
    print(f"Mean confidence: {summary['mean_confidence']:.1f}/5")
    print(f"Mean purity: {summary['mean_purity']:.2f} (std={summary['std_purity']:.2f})")

    print("\nPer-mode accuracy:")
    for mode in VALID_MODES:
        stats = summary["per_mode_accuracy"].get(mode, {})
        acc = stats.get("accuracy", 0)
        n = stats.get("n", 0)
        nc = stats.get("n_correct", 0)
        print(f"  {mode:12s}: {acc:.0%} ({nc}/{n})")

    print("\nConfusion matrix (rows=intended, cols=predicted):")
    labels = summary["confusion_labels"]
    header = "            " + "  ".join(f"{m[:4]:>4s}" for m in labels)
    print(header)
    for i, row in enumerate(summary["confusion_matrix"]):
        print(f"  {labels[i]:10s}  " + "  ".join(f"{v:4d}" for v in row))

    if correlation:
        print(f"\nPurity-signature correlation: r={correlation['purity_distance_correlation']:.3f}")

    if failed_ids:
        print(f"\nWARNING: {len(failed_ids)} failed. Run with --resume to retry.")


if __name__ == "__main__":
    main()
